# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  influxdb-master-01:
    :hostname: "influxdb-master-01"
    :ip: "192.168.40.128"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 10

:groups:
  influxdb-master-01:
    - influxdb-master-01
  servers:
    - influxdb-master-01
  influx_masters:
    - influxdb-master-01
